name: value_stream_flutter
description: Flutter widgets for value_stream.
version: 1.0.0
repository: https://github.com/IcySunStudio/value_stream
issue_tracker: https://github.com/IcySunStudio/value_stream/issues

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  value_stream: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
