name: value_stream
description: Flutter package that provides a set of basic streams with easy access to the latest emitted value
version: 0.0.5
repository: https://github.com/IcySunStudio/value_stream
issue_tracker: https://github.com/IcySunStudio/value_stream/issues

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
